#!/usr/bin/env php

<?php
/**
 * Date: 11.04.2020
 * Time: 13:21
 * Author: Artem Aleksandrov
 */

if (file_exists(__DIR__ . '/../../autoload.php')) {
    require_once __DIR__ . '/../../autoload.php';
} else {
    require_once __DIR__ . '/vendor/autoload.php';
}

use kradwhite\language\command\ConfigCommand;
use kradwhite\language\command\InitCommand;
use kradwhite\language\command\NamesCommand;
use Symfony\Component\Console\Application;

$application = new Application();

$application->addCommands([
    new ConfigCommand(),
    new InitCommand(),
    new NamesCommand()
]);

$application->run();